// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdzGBFpbMvd_K0dFmdqFZvh6loUutroyg',
    appId: '1:802360771642:web:0b1379e49f7d3bbd10e103',
    messagingSenderId: '802360771642',
    projectId: 'cloudanalyzer-b5d18',
    authDomain: 'cloudanalyzer-b5d18.firebaseapp.com',
    storageBucket: 'cloudanalyzer-b5d18.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8qJX_llqazSEQGggSSjNfPlUxP2BDp7M',
    appId: '1:802360771642:android:e550d7d83d94b63a10e103',
    messagingSenderId: '802360771642',
    projectId: 'cloudanalyzer-b5d18',
    storageBucket: 'cloudanalyzer-b5d18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUJFipLnfEvFN_UIaHoIQkZ_9-7dPZFN0',
    appId: '1:802360771642:ios:6e956859149a316e10e103',
    messagingSenderId: '802360771642',
    projectId: 'cloudanalyzer-b5d18',
    storageBucket: 'cloudanalyzer-b5d18.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUJFipLnfEvFN_UIaHoIQkZ_9-7dPZFN0',
    appId: '1:802360771642:ios:6e956859149a316e10e103',
    messagingSenderId: '802360771642',
    projectId: 'cloudanalyzer-b5d18',
    storageBucket: 'cloudanalyzer-b5d18.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdzGBFpbMvd_K0dFmdqFZvh6loUutroyg',
    appId: '1:802360771642:web:041b0992213989f110e103',
    messagingSenderId: '802360771642',
    projectId: 'cloudanalyzer-b5d18',
    authDomain: 'cloudanalyzer-b5d18.firebaseapp.com',
    storageBucket: 'cloudanalyzer-b5d18.firebasestorage.app',
  );
}
